### PR TITLE
added responsive design for projects/details

### LINKED ISSUE #64: Aspect ratios for details page
- set components for different aspect ratios, from small to extra-wide
Screenshot 2024-02-17 at 12 48 06 AM

### LINKED ISSUE #65: Make page responsive
- confirm responsiveness from mobile to extra-wide aspect ratios
Screenshot 2024-02-17 at 12 49 14 AM

### PR DESCRIPTION
**Pull request by JohnZ9865**
Closes #64 
Closes #65 

for details page, tablet screen size:
image
image

for details page, large screen size that had too much white space:
image
image

### CODE REVIEW

**Comment by JohnZ9865** [comment]
image
image

**Comment by fardinzam** [comment]
For Details page:
Screenshot 2024-02-24 at 3 49 52 PM
- headings are not aligned with yellow div

Screenshot 2024-02-24 at 3 51 08 PM
- margins on medium-sized screens are too large

**Comment by JohnZ9865** [comment]
Alr:
1. Made it so that theres no margin for all screen sizes
image
image
image
image
image
image
2. Aligned the yellow things as well.

**Comment by JohnZ9865** [comment]
Ok also the project cards are working now size wise: 
image
image
image
image

**Pull request merged**
