### PR TITLE
Kevinloritsch/search

### PR DESCRIPTION
**Pull request by Kevinloritsch**
image

### CODE REVIEW

**Comment by fardinzam** [comment]
Add the search icon, the delete icon will be another issue
Screenshot 2024-01-15 at 10 19 03 PM

**Comment by Kevinloritsch** [comment]
image

**Comment by Kevinloritsch** [comment]
image

**Comment by fardinzam** [comment]
this branch hasn't been updated, run pull from dev and push the updated branch

**Comment by Kevinloritsch** [comment]
I think I did what you wanted with pulling from dev? Not 100% sure though. Sorry about all the extra changes!

**Pull request merged**
